---
title: Bloque Constitucional
motto: Abogados responsables | Acceso a la justicia | Libre colegiación
permalink: "/:title/"
locale: es_US
url: https://bloqueconstitucional.github.io
email: bloqueconstitucional@hotmail.com
facebook_link: https://facebook.com/bloqueconstitucional.argentina/
twitter_link: https://twitter.com/BloqueConst
instagram_link: https://instagram.com/bloqueconsti
youtube_link: https://youtube.com/___
spotify_link: https://open.spotify.com/show/0LFq9EYg4K3sMvxoNmi2yV?si=VKDIGDiETumLOMT6ZBjyBA
collections:
  miembros:
    output: true
  eventos:
    output: true
  candidatos:
    output: true
  publicaciones:
    output: true
  campaign:
    output: false
campaign_name: Campaña CPACF 2020
is_campaign: false
plugins:
- jekyll-feed
- jekyll-tagories
keep_files:
- ".git"
- ".gitignore"
- CNAME
sass:
  sass_dir: _sass
  style: compressed
exclude:
- vendor/bundle
- TODO
words_per_minute: 300
