---
title: Bloque Constitucional
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
motto: Libre colegiación | Abogados responsables | Acceso a la justicia
permalink: "/:title/"
locale: es_US
url: https://bloqueconstitucional.github.io
email: bloqueconstitucional@hotmail.com
facebook_link: https://facebook.com/bloqueconstitucional.argentina/
twitter_link: https://twitter.com/BloqueConst
instagram_link: https://instagram.com/bloqueconsti
youtube_link: https://youtube.com/___
current_campaign: CPACF_2020
collections:
  miembros:
    output: true
  eventos:
    output: true
  campaign:
    output: true
plugins:
- jekyll-feed
- jekyll-tagories
keep_files:
- ".git"
- ".gitignore"
- CNAME
sass:
  sass_dir: _sass
  style: compressed
exclude:
- vendor/bundle
- TODO
