---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _acciones
  label: Acciones
  create: documents
  match: "**/*"
  templates:
  - post-largo
- type: document
  path: propuesta/index.md
  label: "¿Qué es Bloque Constitucional?"
- type: directory
  path: _publicaciones
  label: Posts largos
  create: documents
  match: "**/*"
  templates:
  - post-largo
- type: directory
  path: _miembros
  label: Miembros
  create: documents
  match: "**/*"
  templates:
  - miembro
- type: document
  path: cargos/index.md
  label: Cargos
- type: document
  path: propuesta-campaign/index.md
  label: Propuesta de Campaña
- type: directory
  path: _candidatos
  label: Candidatos de Campaña (principales)
  create: documents
  match: "**/*"
  templates:
  - candidato-de-campana
- type: document
  path: candidatos/index.md
  label: Candidatos de Campaña (secundarios)
- type: directory
  path: _posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: _eventos
  label: Eventos
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - evento
- type: document
  path: _config.yml
  label: Config General
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
