---
label: Config General
hide_body: true
fields:
- type: text
  name: title
  label: title
  hidden: true
- type: text
  name: motto
  label: motto
- type: text
  name: permalink
  label: permalink
  hidden: true
- type: text
  name: locale
  label: locale
  hidden: true
- type: text
  name: url
  label: url
  hidden: true
- type: text
  name: email
  label: email
- type: text
  name: facebook_link
  label: facebook_link
- type: text
  name: twitter_link
  label: twitter_link
- type: text
  name: instagram_link
  label: instagram_link
- type: text
  name: youtube_link
  label: youtube_link
- type: field_group
  name: collections
  label: collections
  fields:
  - type: field_group
    name: miembros
    label: miembros
    fields:
    - type: boolean
      name: output
      label: output
      hidden: true
    hidden: true
  - type: field_group
    name: eventos
    label: eventos
    fields:
    - type: boolean
      name: output
      label: output
  - type: field_group
    name: campaign
    label: campaign
    fields:
    - type: boolean
      name: output
      label: output
  hidden: true
- type: list
  name: plugins
  label: plugins
  hidden: true
- type: list
  name: keep_files
  label: keep_files
  hidden: true
- type: field_group
  name: sass
  label: sass
  fields:
  - type: text
    name: sass_dir
    label: sass_dir
  - type: text
    name: style
    label: style
  hidden: true
- type: list
  name: exclude
  label: exclude
  hidden: true
- name: is_campaing
  type: boolean
  label: En campaña
- name: campaign
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Nombre de Campaña
  showOnly:
    value: true
- name: spotify_link
  type: text
  config:
    required: false
  label: spotify_link
pages:
- _config.yml
